project:
  type: website

website:
  title: "Amirah Hamid"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: Publications.qmd
        text: Publications
      - href: LifeHub.qmd
        text: Life Hub
  page-footer:
    left: "Copyright 2024 © Amirah Hamid. Developed with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
